variable "name_prefix" {
  description = "Prefix applied to every resource name."
  type        = string
}

variable "db_subnet_group_name" {
  description = "RDS DB subnet group covering the private database subnets."
  type        = string
}

variable "vpc_security_group_ids" {
  description = "Security groups attached to the instance."
  type        = list(string)
}

variable "kms_key_arn" {
  description = "CMK for storage, Performance Insights and the credential secret."
  type        = string
}

# ------------------------------- Engine ------------------------------------

variable "engine_version" {
  description = "PostgreSQL version. A major-only value (e.g. \"16\") lets AWS choose the latest minor."
  type        = string
  default     = "16"
}

variable "parameter_group_family" {
  description = "Parameter group family. Must match the engine major version."
  type        = string
  default     = "postgres16"
}

variable "instance_class" {
  description = "Instance class. db.t4g.* is Graviton and burstable -- fine for a lab."
  type        = string
  default     = "db.t4g.medium"
}

variable "db_name" {
  description = "Name of the initial database created inside the instance."
  type        = string
  default     = "appdb"
}

variable "db_port" {
  description = "PostgreSQL listener port."
  type        = number
  default     = 5432
}

variable "master_username" {
  description = "Master username."
  type        = string
}

variable "master_password" {
  description = "Master password (generated by the security module)."
  type        = string
  sensitive   = true
}

variable "secret_arn" {
  description = "Secrets Manager secret to enrich with the resolved endpoint."
  type        = string
}

# ------------------------------- Storage -----------------------------------

variable "allocated_storage" {
  description = "Initial storage in GiB."
  type        = number
  default     = 50
}

variable "max_allocated_storage" {
  description = "Ceiling for storage autoscaling in GiB. Set equal to allocated_storage to disable."
  type        = number
  default     = 200
}

variable "storage_type" {
  description = "gp3 gives predictable baseline IOPS without provisioning io1/io2."
  type        = string
  default     = "gp3"
}

# ---------------------------- Availability ---------------------------------

variable "multi_az" {
  description = "Synchronous standby in a second AZ. Required for the Phase 4 failover lab."
  type        = bool
  default     = true
}

variable "deletion_protection" {
  description = "Block accidental deletion. scripts/destroy.sh clears this first."
  type        = bool
  default     = true
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. false is the production posture."
  type        = bool
  default     = false
}

variable "apply_immediately" {
  description = "Apply modifications outside the maintenance window. Useful in a lab, dangerous in production."
  type        = bool
  default     = false
}

# ------------------------------- Backup ------------------------------------

variable "backup_retention_period" {
  description = "Days of automated backups. Also the width of the PITR window used in Phase 5."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_period >= 1 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 1 and 35 for PITR to work."
  }
}

variable "backup_window" {
  description = "Daily backup window, UTC. Must not overlap maintenance_window."
  type        = string
  default     = "07:00-08:00"
}

variable "maintenance_window" {
  description = "Weekly maintenance window, UTC."
  type        = string
  default     = "sun:08:30-sun:09:30"
}

variable "copy_tags_to_snapshot" {
  description = "Propagate instance tags onto snapshots so restores stay attributable."
  type        = bool
  default     = true
}

# ----------------------------- Observability -------------------------------

variable "monitoring_interval" {
  description = "Enhanced Monitoring granularity in seconds (0 disables; 1, 5, 10, 15, 30, 60 valid)."
  type        = number
  default     = 30

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.monitoring_interval)
    error_message = "monitoring_interval must be one of 0, 1, 5, 10, 15, 30, 60."
  }
}

variable "performance_insights_retention_period" {
  description = "Performance Insights retention in days. 7 is the free tier."
  type        = number
  default     = 7
}

variable "enabled_cloudwatch_logs_exports" {
  description = "PostgreSQL log types shipped to CloudWatch Logs."
  type        = list(string)
  default     = ["postgresql", "upgrade"]
}

variable "log_retention_days" {
  description = "Retention applied to the exported RDS log groups."
  type        = number
  default     = 14
}

variable "log_min_duration_statement_ms" {
  description = <<-EOT
    Statements slower than this (ms) are logged. 1000 catches the Phase 7 bad
    queries without drowning the log group. -1 disables.
  EOT
  type        = number
  default     = 1000
}

variable "auto_minor_version_upgrade" {
  description = "Let AWS apply minor engine upgrades during the maintenance window."
  type        = bool
  default     = true
}

variable "tags" {
  description = "Tags merged onto every resource."
  type        = map(string)
  default     = {}
}
